# Site settings
baseurl = "http://jerefrer.github.io/lesthesauprintemps/"
languageCode = "fr-fr"
title = "Les Thés au Printemps"
theme = "hugo-agency-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[blackfriday]
  hrefTargetBlank = true

[params]

  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
  name = "Gaël Kellerson"
  description = "Un mec qu'il est bien"

  # Since this template is static, the contact form uses www.formspree.io as a
  # proxy. The form makes a POST request to their servers to send the actual
  # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
  email = "lesthesauprintemps@gmail.com"


  # Navigation
  [params.navigation]
    brand = "Les Thés au Printemps"
    # services = "Le programme"
    # portfolio = "Portfolio"
    about = "Les thèmes"
    contact = "Nous contacter"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #    url = "http://gohugo.io"
    #    name = "Hugo"
    #    weight = 10



  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "Un festival autour du Thé pour un monde en Paix"
    subtitle = "7 et 8 mai à Plazac"
    buttonText = "Découvrez le programme"


  # Services section
  [params.services]
    enable = false
    title = "Thèmes"
    subtitle = "C'est bien."

      [[params.services.row]]

        [[params.services.row.list]]
          icon = "fa-shopping-cart"
          title = "E-Commerce"
          description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

        [[params.services.row.list]]
          icon = "fa-laptop"
          title = "Responsive Design"
          description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

        [[params.services.row.list]]
          icon = "fa-lock"
          title = "Web"
          description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

  # Portfolio section
  [params.portfolio]
    enable = false
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Portfolio"
    subtitle = "Lorem ipsum dolor sit amet consectetur."

    [params.portfolio.modal]
      date = "Date"
      buttonText = "Fermer"


  # About section
  [params.about]
    enable = true
    title = "Thèmes"
    subtitle = "L'Ésprit du Thé : Harmonie, Respect, Pureté, Sérénité"
    endpoint = "Mais<br>surtout<br> *...* Vous !"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    [[params.about.events]]
      class = "the-des-femmes"
      img = "myrrha.jpg"
      date = "7 et 8 Mai"
      title = "Le Thé des Femmes"
      subtitle = "L'esprit du thé au coeur de la féminité."
      description = "L'esprit du thé au coeur de la féminité."
      body = '''
* ![Myrrha](img/myrrha.jpg)<span><h3>Exposition et présence de Myrrha</h3><em>Sur les deux jours</em>http://www.latelierdemyrrha.com/</span>
* <span><h3>Ateliers et partages avec «Les Femmes à la Source» (Festival du Féminin)</h3><em>Ateliers de Wu Tao Samedi à 10h30 et 14h20</em>http://www.femininaupaysdelhomme.com/</span>![Les Femmes à la Source](img/femmesalasource.jpg)
* ![Kayvalia](img/amma.jpg)<span><h3>Partages avec Joy Kaivalya</h3><em>Sur les deux jours</em>Partages avec Joy Kaivalya qui vit auprès de Amma depuis une dizaine d'années, et s'occupe de l'ONG Amrita Serve.</span>
* <span><h3>Présentation de l'ONG Amrita Serve</h3><em>Samedi matin 11h40, salle des fêtes</em>http://amritaserve.org/</span>![AmritaServe](img/amritaserve.jpg)
* ![Balade botanique](img/balade-botanique-femmes.jpg)<span><h3>Plantes sauvages et cycle féminin par Françoise Raso</h3><em>Départ Samedi matin 10h30 du pôle du Thé des femmes</em>Cette balade vous invite à découvrir, à reconnaître et à utiliser quelques plantes et arbres sauvages qui permettent d’harmoniser les déséquilibres induits par les fluctuations hormonales du cycle féminin.</span>
* <span><h3>Plantes sauvages medicinales et comestibles par Françoise Raso</h3><em>Départ Samedi 14h30 et Dimanche 15h du pôle Thé des Femmes</em>Cette balade vous invite à faire connaissance avec les plantes sauvages qui parsèment nos prés et nos bois. Découvrez leurs étonnantes vertus, la manière de les cueillir et de les préparer afin de soigner quelques maux communs et de croquer quelques mets étonnants.</span>![Balade botanique](img/balade-botanique.jpg)
'''

    [[params.about.events]]
      class = 'education'
      img = "education.jpg"
      date = "8 Mai"
      title = "Éducation & Respect de la Vie sur Terre"
      subtitle = "Le respect dans l'éducation."
      description = "Le respect dans l'éducation."
      body = '''

* ![Respect de la vie animale](img/respect-vie-animale.jpg)<span><h3>Stands d'associations pour le respect de la vie animale</h3><em>Sur les deux jours sous la halle du village</em><ul><li>Association arche de Noé</li><li>[Association arche d'Abraham](https://www.facebook.com/profile.php?id=100010940253118&fref=ts)</li><li>[Association végétarienne de France](http://www.vegetarisme.fr/)</li></ul></span>
* <span><h3>Triple exposition des élèves du collège de Montignac</h3><em>Sur les deux jours sous la halle du village</em><ul><li>Le Respect de la vie animale</li><li>La Paix dans le Monde</li><li>Voir Demain dans une tasse de Thé</li></ul></span>![Respect de la vie animale](img/dessin2.jpg)
* ![Table ronde de partages libres](img/table-ronde.jpg)<span><h3>Table ronde de partages libres sur les thèmes de l'art, de l'éducation et du respect de la vie.</h3><em>Sur les deux jours sous la halle du village</em></span>
* <span><h3>Atelier d'expression libre artistique</h3><em>Samedi à 16h</em></span>![Expression libre artistique](img/expression-artistique.jpg)
* ![Je suis la piste](img/je-suis-la-piste.jpg)<span><h3>Départ de l'atelier pistage avec Francis Collie</h3><em>Dimanche à 10h30</em>http://jesuislapiste.fr</span>
* <span><h3>Conférence / débat autour de l'éducation</h3><em>Dimanche 11h à la salle des fêtes</em>Interventions de Christelle Kouch, discipline positive, Sarah Neïma Djerbi, pédagogie Freinet, Nicolas Serre, et Nadège Tricard, présidente des Parents d'élève du collège du Bugue suivies d'un débat ouvert</span>![Conférence éducation](img/conference-education.jpg)
'''

    [[params.about.events]]
      class = 'societe-en-transition'
      img = "societe-en-transition.jpg"
      date = "8 Mai"
      title = "Une société en transition"
      subtitle = "\"L'art du thé se trouve au coeur de la démocratie Japonaise\" Esprit du Thé, Vie du Thé"
      description = "\"L'art du thé se trouve au coeur de la démocratie Japonaise\" Esprit du Thé, Vie du Thé"
      body = '''
* ![Troc de graines](img/troc-graines2.jpg)<span><h3>Troc de Graines et Plantes</h3><em>Sur les deux jours</em>Venez partager vos graines et vos plantes, pour embellir et enrichir les jardins.</span>
* <span><h3>Gratiféria, une nouvelle façon de partager : comme un vide grenier, mais gratuit !</h3><em>Sur les deux jours</em>Venez avec vos objets, vêtements, disques, ... dont vous ne vous servez plus, peut être qu'ils plairont à quelqu'un, et quelque chose vous plaira sûrement sur place !</span>![Gratuit](img/gratuit.jpg)
* ![Jardin](img/jardin.jpg)<span><h3>Expo « jardiner sans phytosanitaire »</h3><em>Samedi</em></span>
* <span><h3>Partage des femmes de l'asso «Les Femmes à la Source»</h3><em>Samedi à 16h</em>Les rencontres de la vie ont conduit ces femmes à organiser un festival du féminin, une aventure qui a changé leurs vies, elles partagent ici leur histoire.</span>![Les Femmes à la Source](img/femmesalasource.jpg)
* ![Sourrou](img/sourrou.jpg)<span><h3>Conférence permaculture par Irène Kightley de la ferme de Sourrou</h3><em>Samedi à 18h à la salle des fêtes</em></span>
* <span><h3>Buffet gourmand par Jeanne !</h3><em>Samedi à 19h30</em>Buffet ouvert. 10€/personne</span>![Jeanne](img/jeanne.jpg)
* ![Bambou Do](img/bambou-do.jpg)<span><h3>Présentation de Bambou Do, avec Caelka</h3><em>Dimanche à 13h50</em>http://bambou-do.com/</span>
* <span><h3>Présentation de 6 projets d'éco lieux par le collectif "construction" de l'association CELA</h3><em>Dimanche à 15h à la salle des fêtes</em></span>![CELA](img/cela.png)
* ![Percussions](img/percussions.jpg)<span><h3>Représentation de percus par les personnes accueillies du foyer l'Embellie</h3><em>Dimanche à 18h30</em></span>
* <span><h3>Conférence / débat autour de l'éducation</h3><em>Dimanche 11h à la salle des fêtes</em>Interventions de Christelle Kouch, discipline positive, Sarah Neïma Djerbi, pédagogie Freinet, Nicolas Serre, et Nadège Tricard, présidente des Parents d'élève du collège du Bugue suivies d'un débat ouvert</span>![Conférence éducation](img/conference-education.jpg)
* ![Stéphane](img/stephane.jpg)<span><h3>Des stands présents sur les deux jours</h3><ul><li>Salades extras de Stéphane et ses 14 aromates</li><li>Sorbets maisons de Jérémy</li><li>Tartes et autres délices de Stéphanie</li><li>Gâteaux et autres merveilles de Maëlle et Noémie</li></ul></span>
* <span><h3>Des stands d'associations locales</h3><ul><li>[Association Céla](http://cela.site/)</li><li>[Groupe local Colibris Bergerac](http://www.colibris-lemouvement.org/)</li><li>[Maison 24](http://lamaison24.fr/)</li><li>[Les chemins de yuna](http://sarlat2012.wix.com/lechemindeyuna)</li><li>[Les arbres du Périgord](http://arborethic.com/arbresperigord/)</li><li>[La NEF](https://www.lanef.com/)</li><li>[Collectif Compteurs Communicants 24](http://collectifcompteurscommunicants24.blogspot.com/)</li><li>Collectif transition 24</li></ul></span>![Maison24](img/maison24.jpg)
* ![Final](img/final.jpg)<span><h3>Final</h3><em>Dimanche à 19h</em></span>
'''

    [[params.about.events]]
      class = 'salle-des-fetes'
      img = "salle-des-fetes.jpg"
      date = "7 Mai"
      title = "Salle des fêtes"
      subtitle = "Au coeur de l'Ésprit du Thé."
      description = "Au coeur de l'Ésprit du Thé."
      body = '''
* ![Vente de thé](img/vente-the.jpg)<span><h3>Vente de thé et présentation de thé rares</h3><em>Sur les deux jours</em></span>
* <span><h3>Expo et poteries de Sophie La Tere en Feu</h3><em>Sur les deux jours</em></span>![Terre en feu](img/terre-en-feu.jpg)
* ![AmritaServe](img/amritaserve.jpg)<span><h3>Présentation de l'ONG Amrita Serve</h3><em>Samedi à 11h40</em>http://amritaserve.org/</span>
* <span><h3>Projection du film HUMAN de Yann Arthus-Bertrand, première partie</h3><em>Samedi à 14h</em></span>![Human](img/human1.jpg)
* ![Cérémonie du thé](img/ceremonie-the.jpg)<span><h3>Cérémonie du thé et présentation de la Voie du Thé par Matthieu Mayer</h3><em>Samedi à 15h</em>(l'art du thé étant aussi un art olfactif, il est demandé aux personnes qui souhaitent participent à la cérémonie du thé de ne pas porter de parfum)</span>
* <span><h3>Projection du film HUMAN de Yann Artus-Bertrand, deuxième partie</h3><em>Samedi à 16h</em></span>![Human](img/human2.jpg)
* ![Sourrou](img/sourrou.jpg)<span><h3>Conférence permaculture par Irène Kightley de la ferme de Sourrou</h3><em>Samedi à 18h</em></span>
* <span><h3>Buffet gourmand par Jeanne !</h3><em>Samedi à 19h30</em>Buffet ouvert. 10€/personne</span>![Jeanne](img/jeanne.jpg)
* ![Surprise](img/surprise.jpg)<span><h3>Soirée Surprise</h3><em>Samedi à 21h</em></span>
* <span><h3>Conférence / débat autour de l'éducation</h3><em>Dimanche à 11h</em>Interventions de Christelle Kouch, discipline positive, Sarah Neïma Djerbi, pédagogie Freinet, Nicolas Serre, et Nadège Tricard, présidente des Parents d'élève du collège du Bugue suivies d'un débat ouvert</span>![Conférence éducation](img/conference-education.jpg)
* ![Cérémonie du thé](img/ceremonie-the.jpg)<span><h3>Cérémonie du Thé GONGFU CHA par Matthieu Mayer</h3><em>Dimanche à 14h20</em></span>
* <span><h3>Présentation de 6 projets d'éco lieux par le collectif "construction" de l'association CELA</h3><em>Dimanche à 15h</em></span>![CELA](img/cela.png)
* ![Impro battle théatre](img/impro.jpg)<span><h3>Impro battle de théâtre par la troupe du festival NOW</h3><em>Dimanche à 17h40</em></span>
'''

  # Team section
  [params.team]
    enable = false
    title = "Our amazing team"
    subtitle = "Lorem ipsum dolor sit amet consectetur."
    description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde."

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    [[params.team.members]]
      img = "1.jpg"
      name = "Kay Garland"
      position = "Lead Designer"
      social = [
        ["fa-twitter", "#"],
        ["fa-facebook", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.team.members]]
      img = "2.jpg"
      name = "Larry Parker"
      position = "Lead Marketer"
      social = [
        ["fa-twitter", "#"],
        ["fa-facebook", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.team.members]]
      img = "3.jpg"
      name = "Diana Pertersen"
      position = "Lead Developer"
      social = [
        ["fa-twitter", "#"],
        ["fa-facebook", "#"],
        ["fa-linkedin", "#"]
      ]

  # Client section
    [params.clients_list]
        enable = true

      # All the clients' logos are stored under 'static/img/logos'.
      # Replace them with your clients's logos.
      [[params.clients]]
        logo = "colibris.jpg"
        link = "http://www.colibris-lemouvement.org/"

      [[params.clients]]
        logo = "lagencecom.jpg"
        link = "http://lagencecom.fr/"

      [[params.clients]]
        logo = "si-nature.jpg"
        link = "http://www.si-nature.fr/"

      [[params.clients]]
        logo = "sinensis.jpg"

      [[params.clients]]
        logo = "plazac.jpg"
        link = "http://www.plazac.fr/"

      [[params.clients]]
        logo = "vallee-de-l-homme.jpg"
        link = "http://www.cc-valleedelhomme.fr/"

      [[params.clients]]
        logo = "conseil-general-dordogne.jpg"
        link = "https://www.dordogne.fr/"


  # Contact section
  [params.contact]
    enable = true
    title = "Pour plus d'informations sur l'événement"
    subtitle  = "Contactez nous !"
    phone = "06 73 79 85 21"
    email = "lesthesauprintemps@gmail.com"
    buttonText = "Envoyer"

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Votre nom *"
      warning = "Entrer votre nom."

    [params.contact.form.email]
      text = "Votre Email *"
      warning = "Entrer votre email"

    [params.contact.form.phone]
      text = "Votre numéro de téléphone *"
      warning = "Entrer votre numéro de téléphone."

    [params.contact.form.message]
      text = "Votre message *"
      warning = "Entrez votre message."


  # Footer section
  [params.footer]
        enable = true
    copyright = "Les Thés au Printemps"


    [[params.footer.social]]
      icon = "fa-facebook"
      link = "https://www.facebook.com/lesthesauprintemps"

